# Generated by Django 2.1.2 on 2018-10-27 12:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='streaming_episodes',
        ),
        migrations.AddField(
            model_name='anime',
            name='streaming_episodes_JSON',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
