# Generated by Django 2.1.2 on 2018-10-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0002_auto_20181027_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='banner_image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
