# Generated by Django 2.1.2 on 2018-10-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0003_anime_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='is_adult',
            field=models.BooleanField(null=True),
        ),
    ]
