# Generated by Django 2.1.2 on 2018-10-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0004_anime_is_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='media_format',
            field=models.CharField(choices=[('TV', 'TV'), ('TV_SHORT', 'TV_SHORT'), ('MOVIE', 'MOVIE'), ('SPECIAL', 'SPECIAL'), ('OVA', 'OVA'), ('ONA', 'ONA'), ('MUSIC', 'MUSIC'), ('MANGA', 'MANGA'), ('NOVEL', 'NOVEL'), ('ONE_SHORT', 'ONE_SHORT')], max_length=200, null=True),
        ),
    ]
