# Generated by Django 2.1.2 on 2018-10-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0005_anime_media_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='url',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
