# Generated by Django 2.1.2 on 2018-10-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0006_auto_20181029_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='imageURL_medium',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
