# Generated by Django 2.1.2 on 2018-10-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0007_anime_imageurl_medium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
