# Generated by Django 2.1.2 on 2018-11-29 20:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0008_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='genres_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), null=True, size=None),
        ),
    ]
